version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    networks:
      - urlshortener-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - urlshortener-net

  shortener:
    build: ./shortener
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis
    networks:
      - urlshortener-net

  redirect:
    build: ./redirect
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - shortener
    networks:
      - urlshortener-net

networks:
  urlshortener-net:
    driver: bridge
